routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::middleware('auth')->group(function () {
    Route::resource('product', ProductController::class);
    Route::resource('purchase', PurchaseController::class);

    Route::get('/products', [ProductController::class, 'display'])->name('products');
    Route::get('/search', [ProductController::class, 'search'])->name('product.search');
    
    Route::get('/soldout', [PurchaseController::class, 'soldOut'])->name('purchase.soldout');
    Route::get('/purchased', [PurchaseController::class, 'purchased'])->name('purchase.purchased');
    Route::get('/pending', [PurchaseController::class, 'pending'])->name('purchase.pending');
    Route::get('/request', [PurchaseController::class, 'request'])->name('purchase.request');
    
    Route::get('/profile', [UserController::class, 'profile'])->name('profile');
    Route::get('/profile/edit', [UserController::class, 'editProfile'])->name('profile.edit');
    Route::get('/passwordreset', [UserController::class, 'passwordReset'])->name('password.reset');
    Route::patch('/passwordreset', [UserController::class, 'storeResetPassword'])->name('resetpassword.store_reset');
    Route::patch('/profile/update', [UserController::class, 'update'])->name('profile.update');
    Route::post('/change', [UserController::class, 'change'])->name('user.change');
});


Route::get('auth/google', [UserController::class, 'authGoogle'])->name('auth.google');
Route::get('auth/google/callback', [UserController::class, 'authGoogleCallback'])->name('auth.google.callback');



Route::get('auth/github', [UserController::class, 'authGithub'])->name('auth.github');
Route::get('auth/github/callback', [UserController::class, 'authGithubCallback'])->name('auth.github.callback');
// Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

resources/views/partials/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>
                    document.write(new Date().getFullYear())
                </script> © Yudiz
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/partials/left_sidebar.blade.php
<div class="leftside-menu">

    @if(session('user.change')=='seller')
    <!-- LOGO -->
    <a href="{{ route('products') }}" class="logo text-center logo-light">
        <span class="logo-lg">
            <img src="{{ asset('assets/images/logo.png') }}" alt="" height="16">
        </span>
        <span class="logo-sm">
            <img src="{{ asset('assets/images/logo_sm.png') }}" alt="" height="16">
        </span>
    </a>

    <a href="{{ route('products') }}" class="logo text-center logo-dark">
        <span class="logo-lg">
            <img src="{{ asset('assets/images/logo-dark.png') }}" alt="" height="16">
        </span>
        <span class="logo-sm">
            <img src="{{ asset('assets/images/logo_sm_dark.png') }}" alt="" height="16">
        </span>
    </a>

    @else
    <a href="#" class="logo text-center logo-light">
        <span class="logo-lg">
            <img src="{{ asset('assets/images/logo.png') }}" alt="" height="16">
        </span>
        <span class="logo-sm">
            <img src="{{ asset('assets/images/logo_sm.png') }}" alt="" height="16">
        </span>
    </a>

    <a href="#" class="logo text-center logo-dark">
        <span class="logo-lg">
            <img src="{{ asset('assets/images/logo-dark.png') }}" alt="" height="16">
        </span>
        <span class="logo-sm">
            <img src="{{ asset('assets/images/logo_sm_dark.png') }}" alt="" height="16">
        </span>
    </a>



    @endif

    <!-- LOGO -->

    
    <div class="h-100" id="leftside-menu-container" data-simplebar>

        <!--- Sidemenu -->
        <ul class="side-nav">

            <li class="side-nav-title side-nav-item">Navigation</li>

            @if(session('user.change')=='seller')
            <li class="side-nav-item">
                <a data-bs-toggle="collapse" href="#sidebarDashboards2" aria-expanded="false"
                    aria-controls="sidebarDashboards2" class="side-nav-link">
                    <i class="uil-money-bill-stack"></i>
                    <span class="menu-arrow"></span>
                    <span> Product </span>
                </a>
                <div class="collapse" id="sidebarDashboards2">
                    <ul class="side-nav-second-level">
                        <li>
                            <a href="{{ route('product.create') }}">Create</a>
                        </li>
                        <li>
                            <a href="{{ route('product.index') }}">All Product</a>
                        </li>
                    </ul>
                </div>
            </li>
            @endif

            <li class="side-nav-item">
                <a data-bs-toggle="collapse" href="#sidebarDashboards" aria-expanded="false"
                    aria-controls="sidebarDashboards" class="side-nav-link">
                    <i class="uil-money-bill-stack"></i>
                    <span class="menu-arrow"></span>
                    <span> Purchase </span>
                </a>
                <div class="collapse" id="sidebarDashboards">
                    <ul class="side-nav-second-level">
                        @if(session('user.change')=='seller')
                        
                            <li>
                                <a href="{{ route('purchase.request') }}">Requests</a>
                            </li>
                            <li>
                                <a href="{{ route('purchase.soldout') }}">Sold</a>
                            </li>
                            <li>
                                <a href="{{ route('purchase.index') }}">All</a>
                            </li>
                        @else    
                            <li>
                                <a href="{{ route('purchase.pending') }}">Pending</a>
                            </li>
                            
                            <li>
                                <a href="{{ route('purchase.purchased') }}">Purchased</a>
                            </li>
                        @endif

                        

                     
                        
                    </ul>
                </div>
            </li>


           


           
        </ul>

        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>

resources/views/partials/right_sidebar.blade.php
<div class="end-bar">

    <div class="rightbar-title">
        <a href="javascript:void(0);" class="end-bar-toggle float-end">
            <i class="dripicons-cross noti-icon"></i>
        </a>
        <h5 class="m-0">Settings</h5>
    </div>

    <div class="rightbar-content h-100" data-simplebar>

        <div class="p-3">
            <div class="alert alert-warning" role="alert">
                <strong>Customize </strong> the overall color scheme, sidebar menu, etc.
            </div>

            <!-- Settings -->
            <h5 class="mt-3">Color Scheme</h5>
            <hr class="mt-1" />

            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="color-scheme-mode" value="light"
                    id="light-mode-check" checked>
                <label class="form-check-label" for="light-mode-check">Light Mode</label>
            </div>

            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="color-scheme-mode" value="dark"
                    id="dark-mode-check">
                <label class="form-check-label" for="dark-mode-check">Dark Mode</label>
            </div>


            <!-- Width -->
            <h5 class="mt-4">Width</h5>
            <hr class="mt-1" />
            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="width" value="fluid" id="fluid-check" checked>
                <label class="form-check-label" for="fluid-check">Fluid</label>
            </div>

            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="width" value="boxed" id="boxed-check">
                <label class="form-check-label" for="boxed-check">Boxed</label>
            </div>


            <!-- Left Sidebar-->
            <h5 class="mt-4">Left Sidebar</h5>
            <hr class="mt-1" />
            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="theme" value="default" id="default-check">
                <label class="form-check-label" for="default-check">Default</label>
            </div>

            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="theme" value="light" id="light-check" checked>
                <label class="form-check-label" for="light-check">Light</label>
            </div>

            <div class="form-check form-switch mb-3">
                <input class="form-check-input" type="checkbox" name="theme" value="dark" id="dark-check">
                <label class="form-check-label" for="dark-check">Dark</label>
            </div>

            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="compact" value="fixed" id="fixed-check" checked>
                <label class="form-check-label" for="fixed-check">Fixed</label>
            </div>

            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="compact" value="condensed" id="condensed-check">
                <label class="form-check-label" for="condensed-check">Condensed</label>
            </div>

            <div class="form-check form-switch mb-1">
                <input class="form-check-input" type="checkbox" name="compact" value="scrollable" id="scrollable-check">
                <label class="form-check-label" for="scrollable-check">Scrollable</label>
            </div>

            
        </div> <!-- end padding-->

    </div>
</div>

<div class="rightbar-overlay"></div>

resources/views/partials/topbar.blade.php
<div class="navbar-custom">
    <ul class="list-unstyled topbar-menu float-end mb-0">
        <li class="notification-list">
            <a class="nav-link end-bar-toggle" href="javascript: void(0);">
                <i class="dripicons-gear noti-icon"></i>
            </a>
        </li>
           

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user arrow-none me-0" data-bs-toggle="dropdown" href="#"
                role="button" aria-haspopup="false" aria-expanded="false">
                <span class="account-user-avatar">
                    <img src="{{Auth::user()->profile ? Storage::url(Auth::user()->profile) : asset('assets/images/users/avatar-1.jpg') }}" alt="user-image" class="rounded-circle">
                </span>
                <span>
                    <span class="account-user-name">{{ Auth::user()->name }}</span>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
                <!-- item-->
                <div class=" dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                </div>

                <a href="{{ route('profile') }}" class="dropdown-item">
                    <i class="mdi mdi-account-circle me-1"></i>
                    <span>My Account</span>
                </a>

                <a href="{{ route('password.reset') }}" class="dropdown-item">
                    <i class="uil-key-skeleton-alt"></i>
                    <span>Change Password</span>
                </a>
                @if(session('user.change')=='seller')
                <form action="{{ route('user.change') }}" method="post">
                    @csrf
                    <button type="submit" class="dropdown-item" name="submit" value='buyer'><i class="uil-key-skeleton-alt"></i><span>Buyer</span></button>
                </form>
                @else
   
                    <form action="{{ route('user.change') }}" method="post">
                        @csrf
                        <button type="submit" class="dropdown-item" name="submit" value='seller'><i class="uil-key-skeleton-alt"></i><span>Seller</span></button>
                    </form>
                @endif

           
            

                <!-- item-->
          <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
                                        <i class="mdi mdi-logout me-1"></i>
                 
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
            </div>
        </li>

    </ul>
    <button class="button-menu-mobile open-left">
        <i class="mdi mdi-menu"></i>
    </button>

  

    <div class="app-search dropdown d-none d-lg-block">
        <form method="get" action="{{ route('product.search')}}">
            <div class="input-group">
                <input type="text" class="form-control dropdown-toggle" placeholder="Search..." id="top-search" name="search">
                <span class="mdi mdi-magnify search-icon"></span>
                <button class="input-group-text btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>

   
</div>