routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::middleware('auth')->group(function () {
    Route::resource('product', ProductController::class);
    Route::resource('purchase', PurchaseController::class);

    Route::get('/products', [ProductController::class, 'display'])->name('products');
    Route::get('/search', [ProductController::class, 'search'])->name('product.search');
    
    Route::get('/soldout', [PurchaseController::class, 'soldOut'])->name('purchase.soldout');
    Route::get('/purchased', [PurchaseController::class, 'purchased'])->name('purchase.purchased');
    Route::get('/pending', [PurchaseController::class, 'pending'])->name('purchase.pending');
    Route::get('/request', [PurchaseController::class, 'request'])->name('purchase.request');
    
    Route::get('/profile', [UserController::class, 'profile'])->name('profile');
    Route::get('/profile/edit', [UserController::class, 'editProfile'])->name('profile.edit');
    Route::get('/passwordreset', [UserController::class, 'passwordReset'])->name('password.reset');
    Route::patch('/passwordreset', [UserController::class, 'storeResetPassword'])->name('resetpassword.store_reset');
    Route::patch('/profile/update', [UserController::class, 'update'])->name('profile.update');
    Route::post('/change', [UserController::class, 'change'])->name('user.change');
});


Route::get('auth/google', [UserController::class, 'authGoogle'])->name('auth.google');
Route::get('auth/google/callback', [UserController::class, 'authGoogleCallback'])->name('auth.google.callback');



Route::get('auth/github', [UserController::class, 'authGithub'])->name('auth.github');
Route::get('auth/github/callback', [UserController::class, 'authGithubCallback'])->name('auth.github.callback');
// Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

app/Models/Purchase.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Purchase extends Model
{
    use HasFactory,SoftDeletes;
    protected $fillable = [
        'product_id','buyer_id','seller_id','status',
    ];

    public function seller()
    {
        return $this->belongsTo(User::class, 'seller_id', 'id');
    }

    public function buyer()
    {
        return $this->belongsTo(User::class, 'buyer_id', 'id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }
}

app/Http/Controllers/PurchaseController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\SendPurchasedMail;
use App\Mail\PurchasedMail;
use App\Models\Purchase;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class PurchaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if($request->month){
            $date = explode("-",$request->month);
          
            $purchases = Purchase::where(['seller_id' => Auth::user()->id])->whereMonth('created_at', '=', $date[1])->whereYear('created_at', '=', $date[0])->get();
            
        }elseif($request->year){
            
            $purchases = Purchase::where(['seller_id' => Auth::user()->id])->whereYear('created_at', '=', $request->year)->get();
            
        }elseif($request->week){
            $date = explode(" - ",$request->week);
            $start = date("Y-m-d", strtotime($date[0]));  
            $end = date("Y-m-d", strtotime($date[1]));
            $purchases = Purchase::where(['seller_id' => Auth::user()->id])->whereBetween('created_at', [$start, $end])->get();
                    
        }else{
            $purchases = Purchase::where(['seller_id' => Auth::user()->id])->get();
        }
        return view('purchase.dashboard', compact('purchases'));
       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $input = $request->except('_token');
        Purchase::create($input);
        return redirect()->route('products');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function show(Purchase $purchase)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function edit(Purchase $purchase)
    {
        return view('purchase.edit', compact('purchase'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Purchase $purchase)
    {
        // dd($request);
        $purchase->update([
            'status' => $request->status,
        ]);

        if($request->status == 'purchased'){
            
            SendPurchasedMail::dispatch($purchase)->delay(now()->addSeconds(1));
        }
        session()->put('purchase.update', 'success');
        return redirect()->back();
        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function destroy(Purchase $purchase)
    {
        $purchase->delete();
        session()->put('purchase.delete', 'success');
        return redirect()->route('purchase.index');
    }

    public function soldOut(Request $request)
    {
        if($request->month){
            $date = explode("-",$request->month);
          
            $purchases = Purchase::where(['seller_id' => Auth::user()->id,'status' => 'purchased'])->whereMonth('created_at', '=', $date[1])->whereYear('created_at', '=', $date[0])->get();
            
        }elseif($request->year){
            
            $purchases = Purchase::where(['seller_id' => Auth::user()->id,'status' => 'purchased'])->whereYear('created_at', '=', $request->year)->get();
            
        }elseif($request->week){
            $date = explode(" - ",$request->week);
            $start = date("Y-m-d", strtotime($date[0]));  
            $end = date("Y-m-d", strtotime($date[1]));
            $purchases = Purchase::where(['seller_id' => Auth::user()->id,'status' => 'purchased'])->whereBetween('created_at', [$start, $end])->get();
                    
        }else{
            $purchases = Purchase::where(['seller_id' => Auth::user()->id,'status' => 'purchased'])->get();
        }
       
        return view('purchase.sold', compact('purchases'));
    }

    public function purchased(Request $request)
    {   
        
        if($request->month){
            $date = explode("-",$request->month);
          
            $purchases = Purchase::where(['buyer_id' => Auth::user()->id,'status' => 'purchased'])->whereMonth('created_at', '=', $date[1])->whereYear('created_at', '=', $date[0])->get();
            
        }elseif($request->year){
            
            $purchases = Purchase::where(['buyer_id' => Auth::user()->id,'status' => 'purchased'])->whereYear('created_at', '=', $request->year)->get();
            
        }elseif($request->week){
            $date = explode(" - ",$request->week);
            $start = date("Y-m-d", strtotime($date[0]));  
            $end = date("Y-m-d", strtotime($date[1]));
            $purchases = Purchase::where(['buyer_id' => Auth::user()->id,'status' => 'purchased'])->whereBetween('created_at', [$start, $end])->get();
                    
        }else{
            $purchases = Purchase::where(['buyer_id' => Auth::user()->id,'status' => 'purchased'])->get();
        }
        


        return view('purchase.purchased', compact('purchases'));
    }

    public function pending()
    {
        $purchases = Purchase::where(['buyer_id' => Auth::user()->id,'status' => 'pending'])->get();
        return view('purchase.pending', compact('purchases'));
    }

    public function request()
    {
        $purchases = Purchase::where(['seller_id' => Auth::user()->id,'status' => 'pending'])->get();
        return view('purchase.request', compact('purchases'));
    }
}

resources/views/purchase/dashboard.blade.php
@extends('layouts.apps')
 @section('content')

<div class="row">
    <div class="col-12">

        <div class="d-flex justify-content-between align-items-center">
            
        
            <div class="page-title-box">
                <h4 class="page-title">All Purchases</h4>
            </div>         
               
        </div>


        <div class="dropdown btn-group">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center">

                        <div class="col-sm">
                            <div class="mb-3">
                                <label for="payer" class="form-label">Type</label>
                                <select class="form-control" aria-hidden="true" name="type" id="select_type" >
                                        @if (old('type') == 'year')
                                            <option value="year" selected>Year</option>
                                            <option value="month">Month</option>
                                        @elseif(old('type') == 'month')
                                            <option value="year">Year</option>
                                            <option value="month" selected>Month</option>
                                        @else
                                            <option value="">Select</option>
                                            <option value="week">week</option>
                                            <option value="year">Year</option>
                                            <option value="month">Month</option>
                                        @endif
                                  </select>
            
                        
            
                                @if($errors->has('type'))
                            
                                    <div class="text-danger">
                                        Please choose a Type.
                                    </div>
                                @endif
                              </div>
                          </div>
                      </div>
                       
                      <div class="col-sm type" id="year">
                        <div class="mb-3">
                              <label for="payer" class="form-label">Year</label>
                              <form action="{{ URL::current() }}" method="get">

                                <select id="ddlYears" class="form-control" name="year"></select>
                                <input class="form-control date" id="example-year" type="submit">
                            </form>
                          </div>
                      </div>
            
                      <div class="col-sm type" id="month">
                        <div class="mb-3">
                            <label for="month" class="form-label">Month</label>
                            <form action="{{ URL::current() }}" method="get">

                                <input class="form-control" id="example-month" type="month" name="month">
                                <input class="form-control" id="example-month" type="submit">
                            </form>
                            
                        </div>
                      </div>

                      <div class="col-sm type" id="week">
                        <div class="mb-3">
                            <label for="week" class="form-label">Week</label>
                            <form action="{{ URL::current() }}" method="get">

                                <input type="text" class="form-control date" id="singledaterange" data-toggle="date-picker" data-cancel-class="btn-warning" name="week">
                                <input class="form-control" id="example-week" type="submit">
                            </form>
                            
                        </div>
                      </div>
                        
                    </div>
                </div>
            </div>
           
            



        </div>
       
        <table id="datatable-buttons" class="table table-striped dt-responsive nowrap w-100">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Product Name</th>
                    <th>Buyer Name</th>
                    <th>Buyer Number</th>
                    <th>Status</th>
                    <th>Created</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach($purchases as $purchase)
                <tr>
                    <td>{{ $purchase->id }}</td>
                    <td>{{ $purchase->product->name }}</td>
                    <td>{{ $purchase->buyer->name }}</td>
                    <td>{{ $purchase->buyer->number }}</td>
                    <td>{{ $purchase->status }}</td>
                    <td>{{ $purchase->created_at->diffForHumans() }}</td>
                    @if($purchase->status!='purchased')
                    <td class="table-action">
                        <div class="row">
                            <div class="col-3">
                                <button type="submit" class="btn gb-transparent"> <a href="{{ route('purchase.edit',$purchase->id) }}"class="action-icon"><i class="mdi mdi-square-edit-outline"></i></a></button>
                            </div>
                            <div class="col-3">
                                <form method="post" action="{{ route('purchase.destroy',$purchase->id) }}"> 
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn gb-transparent"> <a href="" class="action-icon"> <i class="mdi mdi-delete"></i></a></button>
                                </form>
                            </div>
                            
                          </div>                       
                    </td>
                    @else
                    <td class="table-action">-</td>
                    @endif
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>





@endsection



@section('scripts')

<!-- Success message -->
@if (session('purchase.delete'))

<script>
    toastr.options =
  {
  	"closeButton" : true,
  	"progressBar" : true
  }
  		toastr.success("Deleted successfully");
</script>
{{ session()->forget('purchase.delete') }}
@endif



<!-- Success message -->
@if (session('purchase.update'))

<script>
    toastr.options =
  {
  	"closeButton" : true,
  	"progressBar" : true
  }
  		toastr.success("Updated successfully");
</script>
{{ session()->forget('purchase.update') }}
@endif



<script>
    $(document).ready(function () {
        $('.type').hide();
        
        if($('#select_type').val()=='year'){
            
            $('#year').show();
        }else if($('#select_type').val()=='month'){
            $('#month').show();
        }else if($('#select_type').val()=='week'){
            $('#week').show();
        }
        
        $('#select_type').change(function () {
            $('.type').hide();
            $('#'+$(this).val()).show();
        })
    });
</script>

<script type="text/javascript">
    $(function () {
        //Reference the DropDownList.
        var ddlYears = $("#ddlYears");
 
        //Determine the Current Year.
        var currentYear = (new Date()).getFullYear();
 
        //Loop and add the Year values to DropDownList.
        for (var i = 1950; i <= currentYear; i++) {
            var option = $("<option />");
            option.html(i);
            option.val(i);
            ddlYears.append(option);
        }
    });
</script>



    
@endsection

resources/views/purchase/edit.blade.php
@extends('layouts.apps')
 @section('content')
<div class="row">

    <div class="flex-wrap pt-1">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                   <!-- end nav-->
                    <div class="tab-content">
                        <div class="tab-pane show active" id="basic-form-preview">
                            <form id="purchase" action="{{ route('purchase.update',$purchase->id) }}" method="post"  enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="container">
                                    <div class="row">

                                        <div class="row">

                                            
                                            <div class="col-sm">
                                      
                                                <div class="mb-3">
                                                    <label for="payer" class="form-label">Status</label>
                                                    <select class="form-control select2 select2-hidden-accessible" data-toggle="select2" data-select2-id="select2-data-1-flpv" tabindex="-1" aria-hidden="true" name="status" >
                                                        
                                                        @if($purchase->status == "pending")
                                                        <option value="">Select</option>
                                                        <option value="pending" selected>Pending</option>
                                                        <option value="accepted">Accept</option>
                                                        <option value="rejected">Rejected</option>

                                                        
                                                        @elseif($purchase->status == "accepted")
                                                        <option value="">Select</option>
                                                        <option value="accepted" selected>Accept</option>
                                                        <option value="pending">Pending</option>
                                                        <option value="rejected">Rejected</option>

                                                        @elseif($purchase->status == "rejected")
                                                        <option value="">Select</option>
                                                        <option value="rejected" selected>Rejected</option>
                                                        <option value="accepted">Accept</option>
                                                        <option value="pending">Pending</option>

                                                        
                                                        @elseif($purchase->status == "purchased")
                                                        <option value="">Select</option>
                                                        <option value="rejected" selected>Rejected</option>
                                                        <option value="pending">Pending</option>
                                                        <option value="accepted">Accept</option>
                                                        @endif                                                 
                                                                  
                                                         
                                                          </select>
                                                          @if($errors->has('cat_id'))
                                                  
                                                          <div class="text-danger">
                                                              Please choose a Category.
                                                          </div>
                                                          @endif
                                                </div>
  
                                            </div>

                                            

                                        </div>




                                        <div class="row">
                                            <div class="col-sm">
                                                <button type="submit" class="btn btn-primary">Submit</button>
                                            </div>
                                        </div>

                                        
                                    </div>
                            </form>



                            </div>
                            <!-- end preview-->

                            <!-- end preview code-->
                        </div>
                        <!-- end tab-content-->

                    </div>
                    <!-- end card-body-->
                </div>
                <!-- end card-->
            </div>
        </div>

    </div>


    @endsection 
    
    @section('scripts')

                     
                    
    <!-- Success message -->
    @if (session('purchase.update'))
    
    <script>
        toastr.options =
      {
          "closeButton" : true,
          "progressBar" : true
      }
              toastr.success("Updated successfully");
    </script>
    {{ session()->forget('purchase.update') }}
    @endif
    
    
        
    @endsection
    

resources/views/purchase/pending.blade.php
@extends('layouts.apps')
 @section('content')

<div class="row">
    <div class="col-12">
        <div class="d-flex justify-content-between align-items-center">
            <div class="page-title-box">
                <h4 class="page-title">Pendinng</h4>
            </div>            
        </div>
       
        <table id="datatable-buttons" class="table table-striped dt-responsive nowrap w-100">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Seller</th>
                    <th>Status</th>
                    <th>Created</th>
                </tr>
            </thead>

            <tbody>
                @foreach($purchases as $purchase)
                <tr>
                    <td>{{ $purchase->id }}</td>
                    <td>{{ $purchase->product->name }}</td>
                    <td>{{ $purchase->seller->name }}</td>
                    <td>{{ $purchase->status }}</td>
                    <td>{{ $purchase->created_at->diffForHumans() }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>





@endsection

resources/views/purchase/request.blade.php
@extends('layouts.apps')
 @section('content')

<div class="row">
    <div class="col-12">
        <div class="d-flex justify-content-between align-items-center">
            <div class="page-title-box">
                <h4 class="page-title">Requests</h4>
            </div>            
        </div>
       
        <table id="datatable-buttons" class="table table-striped dt-responsive nowrap w-100">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Product Name</th>
                    <th>Buyer Name</th>
                    <th>Buyer Number</th>
                    <th>Status</th>
                    <th>Created</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach($purchases as $purchase)
                <tr>
                    <td>{{ $purchase->id }}</td>
                    <td>{{ $purchase->product->name }}</td>
                    <td>{{ $purchase->buyer->name }}</td>
                    <td>{{ $purchase->buyer->number }}</td>
                    <td>{{ $purchase->status }}</td>
                    <td>{{ $purchase->created_at->diffForHumans() }}</td>
                    <td class="table-action">
                        <div class="row">
                            <div class="col-3">
                                <button type="submit" class="btn gb-transparent"> <a href="{{ route('purchase.edit',$purchase->id) }}"class="action-icon"><i class="mdi mdi-square-edit-outline"></i></a></button>
                            </div>
                            <div class="col-3">
                                <form method="post" action="{{ route('purchase.destroy',$purchase->id) }}"> 
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn gb-transparent"> <a href="" class="action-icon"> <i class="mdi mdi-delete"></i></a></button>
                                </form>
                            </div>
                            
                          </div>                       
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>





@endsection



@section('scripts')

<!-- Success message -->
@if (session('purchase.delete'))

<script>
    toastr.options =
  {
  	"closeButton" : true,
  	"progressBar" : true
  }
  		toastr.success("Deleted successfully");
</script>
{{ session()->forget('purchase.delete') }}
@endif



<!-- Success message -->
@if (session('purchase.update'))

<script>
    toastr.options =
  {
  	"closeButton" : true,
  	"progressBar" : true
  }
  		toastr.success("Updated successfully");
</script>
{{ session()->forget('purchase.update') }}
@endif


    
@endsection