routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::middleware('auth')->group(function () {
    Route::resource('product', ProductController::class);
    Route::resource('purchase', PurchaseController::class);

    Route::get('/products', [ProductController::class, 'display'])->name('products');
    Route::get('/search', [ProductController::class, 'search'])->name('product.search');
    
    Route::get('/soldout', [PurchaseController::class, 'soldOut'])->name('purchase.soldout');
    Route::get('/purchased', [PurchaseController::class, 'purchased'])->name('purchase.purchased');
    Route::get('/pending', [PurchaseController::class, 'pending'])->name('purchase.pending');
    Route::get('/request', [PurchaseController::class, 'request'])->name('purchase.request');
    
    Route::get('/profile', [UserController::class, 'profile'])->name('profile');
    Route::get('/profile/edit', [UserController::class, 'editProfile'])->name('profile.edit');
    Route::get('/passwordreset', [UserController::class, 'passwordReset'])->name('password.reset');
    Route::patch('/passwordreset', [UserController::class, 'storeResetPassword'])->name('resetpassword.store_reset');
    Route::patch('/profile/update', [UserController::class, 'update'])->name('profile.update');
    Route::post('/change', [UserController::class, 'change'])->name('user.change');
});


Route::get('auth/google', [UserController::class, 'authGoogle'])->name('auth.google');
Route::get('auth/google/callback', [UserController::class, 'authGoogleCallback'])->name('auth.google.callback');



Route::get('auth/github', [UserController::class, 'authGithub'])->name('auth.github');
Route::get('auth/github/callback', [UserController::class, 'authGithubCallback'])->name('auth.github.callback');
// Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = [
        'name', 'description', 'price', 'seller_id', 'cat_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'seller_id', 'id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'cat_id', 'id');
    }

    public function images()
    {
        return $this->belongsTo(Image::class,'id','product_id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use App\Models\Purchase;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with('user:id,name', 'category:id,name', 'images:id,path,product_id')->where('seller_id', Auth::user()->id)->get();
        return view('products.dashbord', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {

        $seller_id = ['seller_id' => Auth::user()->id];
        $product = ($request)->merge($seller_id);
        $data = Product::create($product->all());

        if ($file = $request->file('image')) {

            $name = time() . $file->getClientOriginalName();
            $path = $request->image->storeAs('products', $name);
            Image::create([
                'path' => $path,
                'product_id' => $data->id
            ]);
        }
        $request->session()->put('product_added', 'success');
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $purchase = Purchase::where(['buyer_id' => Auth::user()->id, 'product_id' => $product->id])->first();
        return view('products.details', compact('product', 'purchase'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('products.edit', compact('categories', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        // dd($product);

        $product->update($request->all());

        if ($file = $request->file('image')) {

            $name = time() . $file->getClientOriginalName();
            $path = $request->image->storeAs('products', $name);

            $image = Image::where('product_id', $product->id)->first();
            if ($image) {

                $image->update(["path" => $path]);
            } else {
                Image::create([
                    'path' => $path,
                    'product_id' => $product->id
                ]);
            }
        }

        session()->put('product.update', 'success');
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        if ($product->images) {
            Storage::delete('products', $product->images->path);
            $image = Image::where('product_id', $product->id)->first();
            $image->delete();
        }
        session()->put('product.delete', 'success');
        return redirect()->route('product.index');
    }

    public function display(Request $request)
    {
        if ($request->sort == 'price') {
            $products = Product::with('user:id,name', 'category:id,name', 'images:id,path,product_id')->whereNotIn('seller_id', [Auth::user()->id])->orderBy('price', 'DESC')->get();
            $purchases = Purchase::where('buyer_id', Auth::user()->id)->get();
            return view('products.index', compact('products', 'purchases'));
        }
        elseif ($request->sort == 'a_to_z') {
            $products = Product::with('user:id,name', 'category:id,name', 'images:id,path,product_id')->whereNotIn('seller_id', [Auth::user()->id])->orderBy('name', 'ASC')->get();
            $purchases = Purchase::where('buyer_id', Auth::user()->id)->get();
            return view('products.index', compact('products', 'purchases'));
        }elseif ($request->sort == 'recent') {
            $products = Product::with('user:id,name', 'category:id,name', 'images:id,path,product_id')->whereNotIn('seller_id', [Auth::user()->id])->orderBy('created_at', 'DESC')->get();
            $purchases = Purchase::where('buyer_id', Auth::user()->id)->get();
            return view('products.index', compact('products', 'purchases'));
        } elseif ($request->sort == 'category') {
            $products = Product::with('user:id,name', 'category:id,name', 'images:id,path,product_id')->whereNotIn('seller_id', [Auth::user()->id])->get()->sortBy('category.name');
            $purchases = Purchase::where('buyer_id', Auth::user()->id)->get();
            return view('products.index', compact('products', 'purchases'));
        }else {

            $products = Product::with('user:id,name', 'category:id,name', 'images:id,path,product_id')->whereNotIn('seller_id', [Auth::user()->id])->get();
            $purchases = Purchase::where('buyer_id', Auth::user()->id)->get();
            return view('products.index', compact('products', 'purchases'));
        }
    }

    public function search(Request $request)
    {
        $search = $request->search;
        $products = Product::with('user:id,name', 'category:id,name', 'images:id,path,product_id')->whereNotIn('seller_id', [Auth::user()->id])->where('name', 'like', '%' . $search . '%')->get();
        $purchases = Purchase::where('buyer_id', Auth::user()->id)->get();
        return view('products.search', compact('products', 'purchases'));
    }
}

resources/views/products/dashbord.blade.php
@extends('layouts.apps')
 @section('content')

<div class="row">
    <div class="col-12">
        <div class="d-flex justify-content-between align-items-center">
            <div class="page-title-box">
                <h4 class="page-title">All Products</h4>
            </div>
            
                <a href="{{ route('product.create') }}">
                    <button class="btn btn-secondary buttons-print" tabindex="0" aria-controls="datatable-buttons" type="button">
                        <span>Add</span>
                    </button>
                </a>
            
        </div>
       
        <table id="datatable-buttons" class="table table-striped dt-responsive nowrap w-100">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Seller</th>
                    <th>Category</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Created</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach($products as $product)
                <tr>
                    <td>{{ $product->id }}</td>
                    <td><img height="50" src="{{ $product->images ? Storage::url($product->images->path) : 'https://via.placeholder.com/400C/O' }}" alt=""></td>
                    <td>{{ $product->user->name }}</td>
                    <td>{{ $product->category->name }}</td>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->description }}</td>
                    <td>{{ $product->price }}</td>
                    <td>{{ $product->created_at->diffForHumans() }}</td>
                    <td class="table-action">
                        <div class="row">
                            <div class="col-3">
                                <button type="submit" class="btn gb-transparent"> <a href="{{ route('product.edit',$product->id) }}"class="action-icon"><i class="mdi mdi-square-edit-outline"></i></a></button>
                            </div>
                            <div class="col-3">
                                <form method="post" action="{{ route('product.destroy',$product->id) }}"> 
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn gb-transparent"> <a href="" class="action-icon"> <i class="mdi mdi-delete"></i></a></button>
                                </form>
                            </div>
                            
                          </div>                       
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>





@endsection



@section('scripts')

<!-- Success message -->
@if (session('product.delete'))

<script>
    toastr.options =
  {
  	"closeButton" : true,
  	"progressBar" : true
  }
  		toastr.success("Deleted successfully");
</script>
{{ session()->forget('product.delete') }}
@endif



<!-- Success message -->
@if (session('product.update'))

<script>
    toastr.options =
  {
  	"closeButton" : true,
  	"progressBar" : true
  }
  		toastr.success("Updated successfully");
</script>
{{ session()->forget('product.update') }}
@endif

 <!-- Success message -->
 @if (session('product_added'))

 <script>
     toastr.options = {
         "closeButton": true,
         "progressBar": true
     }
     toastr.success("Added successfully");
 </script>
 {{ session()->forget('product_added') }} 
 @endif


    
@endsection

resources/views/products/details.blade.php
@extends('layouts.apps')
@section('content')
<div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">Hyper</a></li>
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                            <li class="breadcrumb-item active">Product Details</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Product Details</h4>
                                </div>
                            </div>
                        </div>
                        <!-- end page title --> 

                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-lg-5">
                                                <!-- Product image -->
                                                <a href="javascript: void(0);" class="text-center d-block mb-4">
                                                    <img src="{{ $product->images ? Storage::url($product->images->path) : 'https://via.placeholder.com/400C/O' }}" class="img-fluid" style="max-width: 280px;" alt="Product-img">
                                                </a>

                                                <!-- <div class="d-lg-flex d-none justify-content-center">
                                                    <a href="javascript: void(0);">
                                                        <img src="assets/images/products/product-1.jpg" class="img-fluid img-thumbnail p-2" style="max-width: 75px;" alt="Product-img">
                                                    </a>
                                                    <a href="javascript: void(0);" class="ms-2">
                                                        <img src="assets/images/products/product-6.jpg" class="img-fluid img-thumbnail p-2" style="max-width: 75px;" alt="Product-img">
                                                    </a>
                                                    <a href="javascript: void(0);" class="ms-2">
                                                        <img src="assets/images/products/product-3.jpg" class="img-fluid img-thumbnail p-2" style="max-width: 75px;" alt="Product-img">
                                                    </a>
                                                </div> -->
                                            </div> <!-- end col -->
                                            <div class="col-lg-7">
                                                
                                                    <!-- Product title -->
                                                    <h3 class="mt-0">{{$product->name}}</h></h3>
                                                    <p class="mb-1">Added Date: {{$product->created_at->diffForHumans()}}</p>
                                                   

                                                    <!-- Product stock -->
                                                    <div class="mt-3">
                                                        <!-- <h4><span class="badge badge-success-lighten">Instock</span></h4> -->
                                                    </div>

                                                    <!-- Product description -->
                                                    <div class="mt-4">
                                                        <h6 class="font-14">Price:</h6>
                                                        <h3> ₹{{$product->price}}</h3>
                                                    </div>

                                                    <div class="col-12">
                                                        <div class="row">
                                                            
                                                            <div class="mt-4 col-3">
                                                                <h6 class="font-14">Description:</h6>
                                                                <p>{{$product->description}} </p>
                                                            </div>
                                                            <div class="mt-4 col-3">
                                                                <h6 class="font-14">Category:</h6>
                                                                <p>{{$product->category->name}}</p> 
                                                            </div>

                                                            <div class="mt-4 col-3">
                                                                <h6 class="font-14">Seller:</h6>
                                                                <p>{{$product->user->name}}</p>
                                                            </div>
                                                        </div>     
                                                    </div>
                                                   

                                        

                                                    @if($purchase=='')

                                                        <form action="{{ route('purchase.store')}}" method="post" enctype="multipart/form-data">
                                                            @csrf
                                                            <input type="text" name="product_id" value="{{$product->id}}" hidden>
                                                            <input type="text" name="seller_id" value="{{$product->seller_id}}" hidden>
                                                            <input type="text" name="buyer_id" value="{{Auth::user()->id}}" hidden>
                                                            <button type="submit" class="btn btn-primary">Request</button> 
                                                        </form>
                                                    @elseif ($purchase->status=='pending')
                                                            <div class="mt-3">
                                                                <h4><span class="badge badge-success-lighten">Pending</span></h4>
                                                            </div>

                                                    @elseif ($purchase->status=='accepted')

                                                        <form action="{{ route('purchase.update',$purchase->id) }}" method="post" enctype="multipart/form-data">
                                                        @method('PUT')    
                                                        @csrf
                                                            <input type="text" name="status" value="purchased" hidden>
                                                            
                                                            <button type="submit" class="btn btn-primary">Buy</button> 
                                                        </form>

                                                        @elseif ($purchase->status=='purchased')
                                                            <div class="mt-3">
                                                                <h4><span class="badge badge-success-lighten">Purchased</span></h4>
                                                            </div>

                                                    @endif
                                            </div> <!-- end col -->
                                        </div> <!-- end row-->

               
                                        
                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                            </div> <!-- end col-->
                        </div>
                        <!-- end row-->
                        
                    </div>


                    @endsection



                    @section('scripts')

                     
                    
                    <!-- Success message -->
                    @if (session('purchase.update'))
                    
                    <script>
                        toastr.options =
                      {
                          "closeButton" : true,
                          "progressBar" : true
                      }
                              toastr.success("Updated successfully");
                    </script>
                    {{ session()->forget('purchase.update') }}
                    @endif
                    
                    
                        
                    @endsection
                    

resources/views/products/search.blade.php
@extends('layouts.apps')
@section('content')
<div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">Hyper</a></li>
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">Projects</a></li>
                                            <li class="breadcrumb-item active">Projects List</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Projects</h4>
                                </div>
                            </div>
                        </div>
                        <!-- end page title --> 

                        <div class="row mb-2">
                            <div class="col-sm-4">
                                <a href="{{ route('product.create') }}" class="btn btn-danger rounded-pill mb-3"><i class="mdi mdi-plus"></i> Create Project</a>
                            </div>
                            {{-- <div class="col-sm-8">
                                <div class="text-sm-end">
                                    <div class="btn-group mb-3">
                                        <button type="button" class="btn btn-primary">All</button>
                                    </div>
                                    <div class="btn-group mb-3 ms-1">
                                        <button type="button" class="btn btn-light">Ongoing</button>
                                        <button type="button" class="btn btn-light">Finished</button>
                                    </div>
                                    <div class="btn-group mb-3 ms-2 d-none d-sm-inline-block">
                                        <button type="button" class="btn btn-secondary"><i class="dripicons-view-apps"></i></button>
                                    </div>
                                    <div class="btn-group mb-3 d-none d-sm-inline-block">
                                        <button type="button" class="btn btn-link text-muted"><i class="dripicons-checklist"></i></button>
                                    </div>
                                </div>
                            </div><!-- end col--> --}}
                        </div> 
                        <!-- end row-->

                        <!-- end row-->
                        
                        <div class="row">
                    
                        @foreach ($products as $product)
              
                            
                               
                            <div class="col-md-6 col-xxl-3">
                                <a href="{{route('product.show',$product->id)}}"><!-- project card -->
                                <div class="card d-block">
                                    <!-- project-thumbnail -->
                                    <img class="card-img-top" src="{{ $product->images ? Storage::url($product->images->path) : 'https://via.placeholder.com/400C/O' }}" alt="project image cap">
                                    <!-- <div class="card-img-overlay">
                                        <div class="badge bg-secondary text-light p-1">Ongoing</div>
                                    </div> -->

                                    <div class="card-body position-relative">
                                        <!-- project title-->
                                        <h4 class="mt-0">
                                            <a href="apps-projects-details.html" class="text-title">{{$product->name}}</a>
                                        </h4>

                                        <!-- project detail-->
                                        <p class="mb-3">
                                            <span class="pe-2 text-nowrap">
                                                <!-- <i class="uil-pricetag-alt"></i> -->

                                                ₹ <b>{{$product->price}}</b> 
                                            </span>
                                            
                                        </p>

                                        <p class="mb-3">
                                            <span class="text-nowrap">
                                                <i class="mdi mdi-comment-multiple-outline"></i>
                                                {{$product->description}}
                                            </span>
                                            
                                        </p>
           
                                        <div>                              
                                  
                            
                                
                                        </div>
                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                                </a>
                                
                            </div> <!-- end col -->

                            
                            @endforeach
                       
                        
                        

                        </div>
                        <!-- end row-->
                        
                    </div>
@endsection